---

- name: Fail if required settings not defined
  fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - "matrix_mx_puppet_slack_appservice_token"
    - "matrix_mx_puppet_slack_homeserver_token"

- name: (Deprecation) Catch and report renamed Slack variables
  fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "item.old in vars"
  with_items:
    - {'old': 'matrix_mx_puppet_slack_container_exposed_port_number', 'new': '<superseded by matrix_mx_puppet_slack_container_http_host_bind_port>'}
