- set_fact:
    matrix_systemd_services_list: "{{ matrix_systemd_services_list + ['matrix-mx-puppet-discord'] }}"
  when: matrix_mx_puppet_discord_enabled|bool

# If the matrix-synapse role is not used, these variables may not exist.
- set_fact:
    matrix_synapse_container_extra_arguments: >
      {{ matrix_synapse_container_extra_arguments|default([]) }}
      +
      ["--mount type=bind,src={{ matrix_mx_puppet_discord_config_path }}/registration.yaml,dst=/matrix-mx-puppet-discord-registration.yaml,ro"]

    matrix_synapse_app_service_config_files: >
      {{ matrix_synapse_app_service_config_files|default([]) }}
      +
      {{ ["/matrix-mx-puppet-discord-registration.yaml"] }}
  when: matrix_mx_puppet_discord_enabled|bool

- block:
  - name: Fail if matrix-nginx-proxy role already executed
    fail:
      msg: >-
        Trying to append MX Puppet Discord's reverse-proxying configuration to matrix-nginx-proxy,
        but it's pointless since the matrix-nginx-proxy role had already executed.
        To fix this, please change the order of roles in your plabook,
        so that the matrix-nginx-proxy role would run after the matrix-bridge-mx-puppet-discord role.
    when: matrix_nginx_proxy_role_executed|default(False)|bool

  - name: Generate MX Puppet Discord proxying configuration for matrix-nginx-proxy
    set_fact:
      matrix_mx_puppet_discord_matrix_nginx_proxy_configuration: |
        location {{ matrix_mx_puppet_discord_public_endpoint }} {
        {% if matrix_nginx_proxy_enabled|default(False) %}
        	{# Use the embedded DNS resolver in Docker containers to discover the service #}
        	resolver 127.0.0.11 valid=5s;
        	set $backend "matrix-mx-puppet-discord:8080";
        	proxy_pass http://$backend;
        {% else %}
        	{# Generic configuration for use outside of our container setup #}
        	proxy_pass http://127.0.0.1:9006;
        {% endif %}
        }

  - name: Register MX Puppet Discord proxying configuration with matrix-nginx-proxy
    set_fact:
      matrix_nginx_proxy_proxy_matrix_additional_server_configuration_blocks: |
        {{
          matrix_nginx_proxy_proxy_matrix_additional_server_configuration_blocks|default([])
          +
          [matrix_mx_puppet_discord_matrix_nginx_proxy_configuration]
        }}
  tags:
   - always
  when: matrix_mx_puppet_discord_enabled|bool

- name: Warn about reverse-proxying if matrix-nginx-proxy not used
  debug:
    msg: >-
      NOTE: You've enabled the MX Puppet Discord bridge but are not using the matrix-nginx-proxy
      reverse proxy.
      Please make sure that you're proxying the `{{ matrix_mx_puppet_discord_public_endpoint }}`
      URL endpoint to the matrix-mx-puppet-discord container.
      You can expose the container's port using the `matrix_mx_puppet_discord_container_http_host_bind_port` variable.
  when: "matrix_mx_puppet_discord_enabled|bool and matrix_nginx_proxy_enabled is not defined"
